import en from './en'

// Portuguese (Brazil). Any newly added key that is not translated here falls
// back to English, preventing untranslated Chinese from reaching users.
export default {
  ...en,
  loading: 'Carregando...',
  nav: { home: 'Início', exchange: 'Estratégia de IA', ticker: 'Mercado', user: 'Usuário' },
  tips: { password: 'A senha deve ter 6 dígitos' },
  empty: { default: 'Nenhum dado disponível', order: 'Nenhuma ordem no momento', bill: 'Nenhum extrato ainda', log: 'Sem registros', robot: 'Nenhum robô', run_robot: 'Não há robôs em execução no momento' },
  homeMenu: {
    item1: { title: 'Autorização de API', sub: 'Acesso com um clique' },
    item2: { title: 'Extrato eletrônico', sub: 'Consulta rápida' },
    item3: { title: 'Central de notícias', sub: 'Atualizações da plataforma' },
    item4: { title: 'Suporte online', sub: 'Ajuda imediata' }
  },
  actions: { cancel: 'Cancelar', confirm: 'Confirmar', submit: 'Enviar', save: 'Salvar', create: 'Criar', view: 'Ver', edit: 'Editar', del: 'Excluir', import: 'Importar', export: 'Exportar', enable: 'Ativar', disable: 'Desativar', copy_success: 'Copiado com sucesso' },
  status: { enabled: 'Ativado', disabled: 'Desativado' },
  finished_text: 'Não há mais dados', bill: 'Extrato', income: 'Receita', platform: 'Plataforma', robot: 'Robô',
  cycle_strategy: 'Estratégia cíclica', single_strategy: 'Estratégia única', expected_return: 'Lucro estimado', latest_news: 'Últimas notícias', add_robot: 'Adicionar robô',
  position_amount: 'Valor da posição', average_price: 'Preço médio das posições', number_calls: 'Número de reforços da posição', number_positions: 'Número de posições', now_price: 'Preço atual', profit_loss: 'Lucro e perda', latest_log: 'Registros recentes', all_log: 'Todos os registros', first_order_amount: 'Valor da primeira ordem', number_of_orders: 'Número de ordens', revue_rate: 'Relação lucro e perda', take_profit_ratio: 'Taxa de realização de lucro', take_profit_retracement: 'Retração do lucro', cover_down: 'Queda para cobertura', cover_pullback: 'Retração da cobertura', setting: 'Configurações', cdkey: 'Código de ativação', sell_out: 'Vender', buy_in: 'Comprar', turnover: 'Volume', number_deals: 'Número de transações', price: 'Preço unitário', closing_time: 'Hora da transação',
  pageRobot: {
    log: 'Registro de transações', order: 'Ordens de negociação', account_related: 'Conta', strategy_related: 'Estratégia', strategy_type: 'Tipo de estratégia', strategic_operations: 'Operações da estratégia', available: 'Saldo disponível ({0})', start: 'Iniciar', pause: 'Pausar', trade_setup: 'Configurações', clearance_sell: 'Encerrar posição', robot_setup: 'Configuração do robô', trade_area: 'Seleção de mercado', dialog_enable: 'Deseja ativar este robô?', dialog_pause: 'Deseja pausar este robô?', dialog_sell: 'Deseja encerrar a posição?'
  },
  pageSign: {
    login_intro: 'Entre no ambiente de negociação para ver estratégias, ativos e atividades.', register_intro: 'Entre no ambiente de criptoativos, conclua o cadastro e conecte seus ativos.', forget_intro: 'Redefina sua senha com um código de verificação e volte para sua conta.', account_security: 'Segurança da conta', phone_placeholder: 'Digite o telefone', email_placeholder: 'Digite o e-mail', password_placeholder: 'Digite a senha', forget_pwd: 'Esqueceu a senha?', account: 'Conta', valid_code: 'Código', send_code: 'Enviar código', code_latest_notice: 'Código enviado. Use o código do e-mail mais recente.', code_sent_title: 'E-mail de verificação enviado', code_sent_notice: 'Se não estiver na caixa de entrada, verifique Spam ou Promoções. Use apenas o código do e-mail mais recente.', pwd: 'Senha', confirm_pwd: 'Confirmar senha', account_err: 'Formato de conta incorreto', pwd_err: 'As duas senhas não coincidem', login_pwd: 'Login com senha', login_code: 'Login com código', phone: 'Telefone', email: 'E-mail', free_reg: 'Cadastrar', has_account: 'Já possui uma conta? Entrar', phone_reg: 'Cadastro por telefone', email_reg: 'Cadastro por e-mail', invitation_code: 'Código de convite', invitation_code_required: 'Digite o código de convite', agreed: 'Li e concordo com o ', agreement: 'Acordo do usuário'
  },
  homeHero: { featured: 'Destaque', live: 'Atualizações ao vivo', platform_news: 'Notícias da plataforma', latest: 'Mais recentes', popular: 'Mercados populares', overview: 'Visão do mercado', plaza: 'Central de estratégias', picks: 'Estratégias em destaque', quant: 'Quant', futures: 'Futuros', spot: 'À vista', grid: 'Estratégia Quant em grade', grid_desc: 'Compre na baixa e venda na alta em mercados voláteis.', tracking: 'Estratégia de acompanhamento inteligente', tracking_desc: 'Acompanhamento inteligente para melhores entradas e saídas.', hedge: 'Arbitragem de hedge', hedge_desc: 'Monitoramento 24 horas para capturar oportunidades de arbitragem.', balance: 'Estratégia de equilíbrio dinâmico', balance_desc: 'Gestão inteligente de posições com controle de risco.', coming: 'Em breve', intro: 'As estratégias quantitativas funcionam continuamente para aproveitar oportunidades de negociação.' },
  homeTicker: { live: 'MERCADO AO VIVO', updated: 'Atualizado', updating: 'Sincronizando...', change24h: '24H', empty: 'Sem dados de mercado' },
  revenuePage: { overview: 'Visão de lucros', intro: 'Analise os detalhes de lucro da estratégia por período.', today: 'Lucro de hoje (USDT)', total: 'Lucro acumulado (USDT)', profit: 'Lucro' },
  pageNews: { title: 'Notícias', eyebrow: 'Notícias da plataforma', heading: 'Atualizações e notícias de mercado', sub: 'Todos os horários são exibidos no horário do leste dos EUA.', loading: 'Carregando...', empty: 'Nenhuma notícia disponível', read_more: 'Ler artigo completo' },
  pageAuthorizeForm: { settings: 'Configurações de API', intro: 'Insira as chaves da plataforma para executar estratégias e sincronizar a conta.', api_key_placeholder: 'Digite a chave da API', secret_key_placeholder: 'Digite a chave secreta', passphrase_placeholder: 'Digite a frase secreta' },
  pageAuthorize: { manage: 'Gerenciamento de autorizações', intro: 'Gerencie APIs de negociação, verifique o status, edite chaves ou adicione uma autorização.', authorized: 'Autorizado e pronto para uso', delete_confirm: 'Excluir esta API da plataforma?', add: 'Adicionar chave de API', not: 'Você não adicionou a API da plataforma', expired: 'A API da plataforma não está mais disponível' },
  pageAuthorizeFuture: { title: 'Autorização de API de futuros', add: 'Adicionar chave de API', not: 'Você não adicionou uma API de futuros', expired: 'A API de futuros não está mais disponível' },
  pageMarket: { market_title: 'Mercado de estratégias', market_intro: 'Veja plataformas, saldos e estratégias disponíveis em um só lugar.', not: 'Você não adicionou a API da plataforma', add: 'Adicionar agora', bind_api_desc: 'Conecte a API da sua corretora para acessar saldos e usar estratégias.', balance: 'Saldo', balance_empty: 'Não há dados de saldo para exibir', loading: 'Carregando saldo', login_required: 'Faça login primeiro', login_required_desc: 'Entre para ver mercados, saldos e estratégias disponíveis.', go_login: 'Ir para login', system_error: 'Indisponível agora', system_error_desc: 'Não foi possível carregar os dados de mercado. Tente novamente mais tarde.', retry: 'Recarregar' },
  pageFuture: { title: 'Estratégia de futuros', contract_balance: 'Futuros', not: 'Você não adicionou uma API de futuros', add: 'Adicionar agora', balance: 'Saldo da conta de margem' },
  pageRobotForm: { tip: 'Saldo mínimo para iniciar o robô', cover_tip: 'Defina a queda que aciona cada ordem de segurança', cover_first: 'Primeira ordem de segurança', cover_step: 'Ordem de segurança {count}', cover_label: 'Configuração de queda', cover_input: 'Digite a porcentagem de queda' },
  pageRobotFutureForm: { tip: 'Saldo mínimo de 1000 USDT para iniciar o robô' },
  pageCaleandar: { log: 'Registro de transações', order: 'Ordens de negociação' },
  pageGoogleValid: { open: 'Ativar agora', close: 'Desativar verificação em duas etapas', tip1: 'A verificação em duas etapas adiciona uma camada extra de proteção e exige um código ao entrar.', help: 'Como usar a verificação em duas etapas', set_code: 'Digite o código recebido no telefone', code_please: 'código de verificação', google: 'Digite o código do Google Authenticator', tip2: 'Guarde a chave de recuperação de 16 dígitos em local seguro. Sem ela não será possível recuperar a verificação.', btn: 'Tenho o dispositivo e fiz backup da chave secreta' },
  pageVerified: { title: 'Verificação', no_pwd: 'Defina uma senha de pagamento', during: 'A verificação de identidade está em análise. Aguarde.', fail: 'A verificação de identidade falhou. Envie novamente.', help: 'Como concluir a verificação', upload_id: 'Envie fotos do documento de identidade' },
  pageVerifiedForm: { title: 'Verificação', nationality: 'Nacionalidade', nationality_please: 'Digite sua nacionalidade', address: 'Endereço', address_please: 'Digite seu endereço', name: 'Nome real', name_please: 'Digite seu nome real', birthday: 'Data de nascimento', birthday_please: 'Selecione a data de nascimento', card: 'Número do documento', card_please: 'Digite o número do documento', card_front: 'Frente do documento', card_back: 'Verso do documento' },
  pageInviteInfo: { total: 'Bônus acumulado por convites', invite: 'Número de amigos convidados', active: 'Número de amigos ativados', number: 'Número de amigos cadastrados', number_1: 'Amigos de primeiro nível', number_2: 'Amigos de segundo nível', number_3: 'Amigos de terceiro nível' },
  pageReferralRank: { title: 'Detalhes de promoção', id: 'ID do usuário', account: 'Conta', level: 'Nível', profit: 'Lucro', time: 'Horário', yeji: 'Desempenho', up_level: 'Promover nível', confirm_upgrade: 'Deseja promover o nível deste usuário?' },
  settingsPage: { title: 'Configurações', info: 'Informações pessoais', bind_phone: 'Vincular telefone', bind_email: 'Vincular e-mail', pwd_login: 'Senha de login', contact: 'Fale conosco', exit: 'Sair', tip: 'Aviso', tip_msg: 'Deseja sair da conta atual?', language: 'Alterar idioma', email: 'E-mail', email_please: 'Digite seu e-mail', code: 'Código', code_please: 'Digite o código', send: 'Enviar código', old: 'Senha antiga', new: 'Nova senha', confirm: 'Confirmar senha', please: 'Digite ', head: 'Avatar', nick: 'Apelido', signature: 'Assinatura', edit_nick: 'Editar apelido', edit_sign: 'Editar assinatura' },
  robotForm: { preset: 'Estratégia predefinida', steady: 'Estável', custom: 'Personalizada', first: 'Digite o valor da primeira ordem', multiple: 'Múltiplo', equal: 'Igual', difference: 'Diferença', orders: 'Digite o número de ordens', times: 'Digite a quantidade de multiplicadores', take_profit: 'Digite a taxa de realização de lucro', retracement: 'Digite a retração de lucro', pullback: 'Digite a retração da ordem de segurança', cdkey: 'Digite o código de ativação', cover_first: 'Primeira ordem de segurança', cover_tip: 'Defina a queda que aciona cada ordem de segurança', cover_step: 'Ordem de segurança {count}', cover_label: 'Configuração de queda', cover_input: 'Digite a porcentagem de queda', cover_required: 'A porcentagem de queda da ordem de segurança é obrigatória' },
  login: 'Entrar', sign_up: 'Cadastrar', asset_name: 'Ativo', up_down: 'Alta/Baixa', price_: 'Preço',
  pageUser: { login: 'Entrar', welcome: 'Bem-vindo ao AI Crypto Star', history: 'Histórico de transações', safety_lv: 'Nível de segurança', google_valid: 'Verificação do Google em duas etapas', cdkey: 'Meu código de ativação', invite: 'Convites', about: 'Acordo do usuário', community: 'Comunidade', account_center: 'Central da conta', tip1: 'Seu status VIP expira em', tip2: 'Seu status VIP expirou!', language: 'Idioma', language_zh: 'Chinês', language_en: 'Inglês', language_pt_br: 'Português (Brasil)', news: 'Notícias', future: 'Futuros', contact: 'Fale conosco' },
  pageInvite: { total: 'Bônus acumulado por cadastro indicado', invite: 'Número de amigos convidados', active: 'Número de amigos ativados', number: 'Número de amigos cadastrados', number_1: 'Amigos de primeiro nível', number_2: 'Amigos de segundo nível', number_3: 'Amigos de terceiro nível', invite_code: 'Código de convite', copy_code: 'Copiar código', copy_link: 'Copiar link', invite_kicker: 'CONVITE', invite_title: 'Meu código de convite', invite_tip: 'Compartilhe o código de convite, o link de cadastro ou o QR Code. Novos usuários entram na sua equipe após o cadastro.', invite_empty_tip: 'Crie seu código de convite abaixo para começar a compartilhar.', qr_title: 'Escaneie para cadastrar', qr_desc: 'Para compartilhar pessoalmente, peça para a pessoa escanear o código e abrir o cadastro.', invite_link: 'Link de cadastro', promotion_pack_title: 'Guia de promoção', promotion_item_code_title: '1. Envie o código primeiro', promotion_item_code_desc: 'Ideal para conversas privadas e grupos. O usuário pode vincular o código no cadastro.', promotion_item_qr_title: '2. Envie o link ou QR Code', promotion_item_qr_desc: 'Ideal para redes sociais, comunidades e apresentação presencial.', promotion_item_result_title: '3. Mostre as páginas de resultado', promotion_item_result_desc: 'Combine com páginas de lucro ou extrato para uma promoção mais completa.', you_level: 'Identidade de agente', partner: 'Parceiro', user: 'Usuário', agent: 'Status de parceiro', ratio: 'Taxa de participação', result: 'Desempenho', yes: 'Sim', no: 'Não', people: 'pessoas', share_tip_title: 'Texto sugerido para promoção', share_tip_1: 'Amigos que se cadastrarem e usarem a plataforma podem receber recompensas em USDT conforme o plano da equipe.', share_tip_2: 'Use o código, link de cadastro, QR Code e página de lucro para uma divulgação consistente.', code_manage_title: 'Meus códigos de convite', code_manage_desc: 'Você pode criar um código pessoal. Códigos adicionais são gerenciados pelo painel administrativo.', create_code: 'Criar código de convite', unlimited: 'Ilimitado', no_codes: 'Não há códigos ativos', create_code_success: 'Código de convite criado', create_code_failed: 'Não foi possível criar o código', disable_code: 'Desativar código', enable_code: 'Ativar código', toggle_code_success: 'Status atualizado' },
  pageActivation: { title: 'Código de ativação', buy: 'Comprar', key: 'Código de ativação', time: 'Data de obtenção', state: 'Usado', robot: 'Robô', buy_title: 'Comprar código de ativação', buy_count: 'Quantidade', trade_pwd: 'Senha de negociação', trade_pwd_placeholder: 'Digite a senha de negociação', buy_confirm: 'Comprar', buy_success: 'Código de ativação comprado' },
  pageActivationPopup: { title: 'Digite o código de ativação', get: 'Obter', key: 'Código de ativação', please: 'Digite o código de ativação', confirm_title: 'Aviso', confirm_msg: 'Deseja resgatar este código?', success: 'Ativado com sucesso' },
  changeLang: 'Alterar idioma'
}
