server {
    server_name neuranet.site www.neuranet.site;

    root /data/lhqb/current/public;
    index index.php index.html;
    charset utf-8;

    access_log /data/lhqb/logs/nginx/lhqb-access.log main;
    error_log  /data/lhqb/logs/nginx/lhqb-error.log warn;

    location = / {
        return 302 /app/;
    }

    location / {
        try_files $uri $uri/ @app;
    }

    location /api/ {
        try_files $uri $uri/ @api;
    }

    location @app {
        rewrite ^/(.*)$ /index.php?s=$1 last;
    }

    location @api {
        rewrite ^/api/(.*)$ /api/index.php?s=$1 last;
    }

    location ~* ^/(upload|plugins|themes)/.+\.(html|php)$ {
        return 404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param APP_DEBUG "false";
        fastcgi_param PHP_ADMIN_VALUE "open_basedir=/data/lhqb/current/:/data/lhqb/releases/:/data/lhqb/shared/:/data/lhqb/logs/:/tmp/";
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
    }

    location ~ /\. {
        deny all;
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/neuranet.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/neuranet.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name neuranet.site www.neuranet.site;

    if ($host = neuranet.site) {
        return 301 https://$host$request_uri;
    }

    return 404;
}
